image: docker:23.0.3

stages:
  - build

build:
  stage: build
  only:
    - tags
  services:
    - docker:23.0.3
  variables:
    IMG_TAG: $CI_REGISTRY_IMAGE/app:$CI_COMMIT_TAG
  script:
    - echo -n $CI_REGISTRY_PASSWORD | docker login --username $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker build --push --progress plain --tag $IMG_TAG $CI_PROJECT_DIR
    - scripts/notify-flux-imgrepo.sh $CI_REGISTRY_IMAGE/app:$CI_COMMIT_TAG
