apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hello-k8s
  name: hello-k8s
spec:
  selector:
    matchLabels:
      service: hello
  template:
    metadata:
      name: hello-k8s
      labels:
        service: hello
    spec:
      containers:
        - name: hello-k8s
          image: localhost:32000/hello-k8s:latest
---
apiVersion: v1
kind: Service
metadata:
  name: hello-k8s
spec:
  selector:
    service: hello
  ports:
    - port: 7777
---
apiVersion: v1
kind: Namespace
metadata:
  name: hello-k8s
