# https://taskfile.dev

version: '3'

tasks:
  seal: sops --age age1vax23pz8usu7u0wt9lv82dexp9nqa45z7py93m463qyyrq85xa4sarqwr0 --encrypt manifests/secret.env > manifests/secret.enc.env

  unseal: sops --decrypt manifests/secret.enc.env > secret2.env

  build: docker buildx build --push --platform linux/amd64,linux/arm64 --tag gitea.klavionik.net/klavionik/hello-k8s:{{.CLI_ARGS}}
