apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      name: hello-k8s
      labels:
        app: hello
    spec:
      containers:
        - name: hello-k8s
          image: gitea.klavionik.net/klavionik/hello-k8s:1.2
          envFrom:
            - secretRef:
                name: secrets
